name: Test
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.32.1

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 24

      - name: Install dependencies
        run: pnpm install

      - name: Validate TypeScript
        run: pnpm run test
